apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mixmanager
  description: Mix Manager Web Client
  annotations:
    github.com/project-slug: JulianSC-01/mixmanager
spec:
  lifecycle: production
  owner: user:juliansc-01
  type: website
